### ISSUE TITLE
List all files and directories

### ISSUE THREAD

**Issue by adrianogf** [singlequote/laravel-webdav#5] opened 2023-09-11 20:10 UTC
I can use $this->files = Storage::disk('webdav')->files() to list all files but the directories don't appear. I tried to use  Storage::disk('webdav')->allFiles() and Laravel throw a error:
Unable to list contents for '', deep listing Reason: Not Found

How can I list all files and directories?

**Comment by wimurk** [comment] 2023-09-12 09:00
Hi @adrianogf, the package is just a driver for the laravel storage engine. 

As for the docs you can use `Storage::disk('webdav')->directories()` or `Storage::disk('webdav')->allDirectories()`
The `files()` and `allFiles()` only show the files within the given path. 

```php
$files = Storage::disk('webdav')->files('path/to/folder');
$folders = Storage::disk('webdav')->directories('path/to/folder');
```

https://laravel.com/docs/10.x/filesystem#get-all-directories-within-a-directory

**Comment by wimurk** [comment] 2023-11-30 07:56
Closing this issue for it is not a bug

**Closed as completed by wimurk** 2023-11-30 07:56 UTC
Labels: question, wontfix
